CREATE TABLE records (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  summary TEXT NOT NULL,
  outcome TEXT NOT NULL CHECK (outcome IN ('proved', 'disproved', 'discovered', 'formalized', 'benchmark')),
  novelty TEXT NOT NULL CHECK (novelty IN ('new-result', 'human-ai', 'rediscovery', 'formalization', 'capability')),
  domain TEXT NOT NULL,
  event_date TEXT NOT NULL,
  ai_system TEXT NOT NULL,
  ai_role TEXT NOT NULL,
  human_role TEXT NOT NULL,
  verification TEXT NOT NULL,
  verification_tier TEXT NOT NULL CHECK (verification_tier IN ('formal', 'published', 'expert', 'reported')),
  caveat TEXT NOT NULL,
  featured INTEGER NOT NULL DEFAULT 0 CHECK (featured IN (0, 1)),
  tags_json TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sources (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  record_id INTEGER NOT NULL REFERENCES records(id) ON DELETE CASCADE,
  kind TEXT NOT NULL CHECK (kind IN ('paper', 'formal-proof', 'announcement', 'expert-review', 'project', 'problem')),
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  is_primary INTEGER NOT NULL DEFAULT 1 CHECK (is_primary IN (0, 1)),
  UNIQUE(record_id, url)
);

CREATE INDEX records_event_date_idx ON records(event_date DESC);
CREATE INDEX records_outcome_idx ON records(outcome);
CREATE INDEX records_domain_idx ON records(domain);
CREATE INDEX records_verification_idx ON records(verification_tier);
CREATE INDEX sources_record_id_idx ON sources(record_id);

INSERT INTO records
  (slug, title, summary, outcome, novelty, domain, event_date, ai_system, ai_role, human_role, verification, verification_tier, caveat, featured, tags_json)
VALUES
  ('jacobian-counterexample-dimension-three', 'Jacobian conjecture counterexample in dimension three', 'An explicit polynomial map from C³ to C³ has constant nonzero Jacobian but three preimages of one point, disproving the conjecture in dimensions three and higher.', 'disproved', 'new-result', 'Algebraic geometry', '2026-07-20', 'Claude Fable 5', 'Generated the decisive explicit construction after the question was proposed.', 'Levent Alpöge checked, announced, and contextualized the result; Akhil Mathew proposed the target question.', 'Two independent Lean formalizations plus expert mathematical review.', 'formal', 'The classical dimension-two Jacobian conjecture remains open.', 1, '["polynomial maps","Jacobian conjecture","Lean"]'),
  ('maxwell-point-charge-counterexample', 'Counterexample to Maxwell’s point-charge critical-point conjecture', 'A five-charge configuration in R³ has at least 24 nondegenerate critical points, exceeding the conjectured bound of 16.', 'disproved', 'human-ai', 'Mathematical physics', '2026-07-29', 'GPT-5.6 Sol', 'Suggested the construction that led to the counterexample.', 'Three mathematicians refined and independently checked the construction with symbolic software.', 'Author-checked preprint and independent computer-algebra verification.', 'expert', 'The AI supplied the key construction, but the final result is a human–AI collaboration.', 1, '["electrostatics","critical points","counterexample"]'),
  ('grothendieck-group-scheme-counterexample', 'Counterexample to a Grothendieck group-scheme question', 'A finite locally free commutative group scheme of order four was constructed that is not annihilated by four.', 'disproved', 'new-result', 'Algebraic geometry', '2026-07-11', 'GPT-5.6 Sol and Claude Fable', 'Produced and refined the counterexample; a formal system checked the construction.', 'Experts translated, audited, and explained the argument.', 'Lean-checked construction with expert review.', 'formal', 'The result answers a narrowly stated historical question, not a broad classification problem.', 0, '["group schemes","Grothendieck","Lean"]'),
  ('erdos-unit-distance-conjecture', 'Erdős unit-distance upper-bound conjecture', 'An infinite family of planar point configurations has n^(1+δ) unit distances for a fixed positive δ, contradicting the conjectured n^(1+o(1)) upper bound.', 'disproved', 'new-result', 'Discrete geometry', '2026-05-20', 'OpenAI internal research model', 'Autonomously searched for and found the construction and proof strategy.', 'OpenAI researchers verified the result and prepared the public mathematical account.', 'Public technical report and expert verification.', 'expert', 'This refutes the proposed upper bound; it does not determine the true extremal growth rate.', 1, '["Erdős","unit distances","extremal geometry"]'),
  ('alphaproof-nexus-open-problems', 'AlphaProof Nexus resolves open Erdős and OEIS problems', 'The strongest evaluated agent resolved 9 of 353 selected open Erdős problems and proved 44 of 492 OEIS conjectures in a large-scale formal study.', 'proved', 'new-result', 'Formal mathematics', '2026-05-21', 'AlphaProof Nexus', 'Searched for proofs and produced Lean-checkable proof terms.', 'Researchers selected tasks, built infrastructure, audited outputs, and reported novelty.', 'Lean kernel checking and paper-level evaluation.', 'formal', 'This is an aggregate study; novelty and mathematical importance vary by problem.', 1, '["Lean","Erdős problems","OEIS","benchmark"]'),
  ('pure-o-sequences-log-concavity', 'Log-concavity for codimension-three pure O-sequences of type two', 'A formally checked proof established log-concavity in the monomial type-two case targeted by the AlphaProof Nexus collaboration.', 'proved', 'new-result', 'Algebraic combinatorics', '2026-05-21', 'AlphaProof Nexus', 'Generated the proof in Lean during an AI-collaborator evaluation.', 'Researchers selected and interpreted the open problem and audited the formal proof.', 'Lean-checked proof published with the evaluation outputs.', 'formal', 'The broader nonmonomial version remains open.', 0, '["O-sequences","log-concavity","Lean"]'),
  ('first-proof-blind-refereeing', 'First Proof blind-refereeing experiment', 'Across ten unpublished research problems and four AI systems, seven problems received at least one referee grade of essentially correct or correct with minor revisions.', 'benchmark', 'capability', 'Research mathematics', '2026-06-10', 'Four frontier AI systems', 'Attempted unseen research problems under controlled conditions.', 'Problem authors supplied unpublished prompts; independent mathematicians refereed anonymized submissions.', 'Blind human refereeing with a published study report.', 'published', 'A passing referee grade is not a blanket priority claim, and several attempts failed or needed repair.', 1, '["blind review","research benchmark","peer review"]'),
  ('first-proof-hilbert-series-hooks', 'Hook coefficients of a universal Hilbert series', 'Three systems independently found correct combinatorial interpretations for a previously unpublished coefficient problem in the First Proof study.', 'proved', 'new-result', 'Algebraic combinatorics', '2026-06-10', 'ProofCouncil, UCLA Moonshot, and ChatGPT 5.5 Pro', 'Produced independent proof approaches and interpretations.', 'The problem author and blind referees assessed the submissions.', 'Blind referee grades of correct with minor revisions.', 'published', 'The study report is the evidence artifact; this entry does not assert independent journal publication.', 0, '["Hilbert series","combinatorics","First Proof"]'),
  ('kourovka-eight-problems', 'Eight Kourovka Notebook problems in group theory', 'Eight longstanding problems from the Kourovka Notebook were solved, including a counterexample to a rank inequality for p-group extensions and results on product values, power graphs, and Rota–Baxter operators.', 'proved', 'new-result', 'Group theory', '2026-07-20', 'Harmonic Aristotle', 'Autonomously discovered proofs and counterexamples and produced Lean formalizations.', 'Authors curated the targets, checked formalizations, and wrote the report.', 'All eight results were Lean verified and released in a preprint.', 'formal', 'This aggregate entry compresses eight distinct theorems and counterexamples; consult the paper for exact statements.', 1, '["Kourovka Notebook","group theory","Lean"]'),
  ('anderson-quasi-completeness', 'D. D. Anderson’s quasi-completeness question', 'A 2014 open problem in commutative algebra about quasi-complete rings was resolved by a paired informal and formal AI workflow.', 'proved', 'new-result', 'Commutative algebra', '2026-04-04', 'Rethlas and Archon', 'Rethlas developed the argument and Archon formalized it in Lean.', 'Researchers supplied the problem and audited the resulting proof.', 'Lean verification and a public preprint.', 'formal', 'The headline concerns one precise ring-theoretic question, not all related completeness notions.', 0, '["commutative algebra","rings","Lean"]'),
  ('fel-polynomial-conjecture', 'Fel’s polynomial conjecture for numerical semigroups', 'A conjectural polynomial identity governing syzygy degrees of numerical semigroups was proved from a natural-language statement and formalized.', 'proved', 'new-result', 'Commutative algebra', '2026-02-05', 'AxiomProver', 'Generated an autonomous proof and Lean 4 formalization.', 'The Axiom Math team evaluated and released the result and source.', 'Lean 4.26 kernel checking with public source.', 'formal', 'Novelty is reported by the authors and should be revisited if prior literature emerges.', 0, '["numerical semigroups","syzygies","Lean"]'),
  ('partial-vandiver-density-one', 'A partial Vandiver theorem for almost all primes', 'A density-one subset of primes was shown to satisfy a partial regularity property related to Vandiver’s conjecture.', 'proved', 'new-result', 'Number theory', '2026-02-04', 'AxiomProver', 'Produced the proof and Lean formalization from the natural-language conjecture.', 'Researchers formulated the target, audited the proof, and released the preprint.', 'Lean-checked formal proof and public preprint.', 'formal', 'This is a partial density-one result, not a proof of Vandiver’s conjecture for every prime.', 0, '["Vandiver conjecture","primes","Lean"]'),
  ('erdos-728-factorial-divisibility', 'Erdős Problem 728: factorial-divisibility gaps', 'A logarithmic-gap theorem for factorial divisibility resolved Erdős Problem 728.', 'proved', 'new-result', 'Number theory', '2026-01-12', 'GPT-5.2 Pro and Aristotle', 'One system developed the argument and the other generated a formal Lean proof.', 'Researchers checked the mathematics and linked it to the original problem.', 'Lean verification and a public preprint.', 'formal', 'The paper calls this the first fully autonomous resolution in its workflow; that historical priority claim is source-attributed.', 0, '["Erdős 728","factorials","Lean"]'),
  ('erdos-659-few-distances', 'Erdős Problem 659: few distances with four-point richness', 'A construction gives n planar points with O(n/sqrt(log n)) distances while every four points determine at least three distances.', 'proved', 'new-result', 'Discrete geometry', '2026-01-13', 'Gemini 3', 'Found a construction and proof resolving the tracked problem.', 'Community maintainers and mathematicians checked and recorded the solution.', 'Lean-checked proof referenced by the community tracker.', 'formal', 'The database follows the current Erdős Problems tracker status; consult its discussion for priority details.', 0, '["Erdős 659","distances","geometry"]'),
  ('erdos-960', 'Erdős Problem 960 counterexample', 'An OpenAI research model produced a counterexample to the statement tracked as Erdős Problem 960.', 'disproved', 'new-result', 'Combinatorics', '2026-04-09', 'OpenAI internal research model', 'Found the counterexample through autonomous mathematical search.', 'Experts and the Erdős Problems community checked and updated the problem status.', 'Expert-checked and tracker-confirmed.', 'expert', 'Use the problem page for the exact quantified statement and current priority notes.', 0, '["Erdős 960","counterexample","combinatorics"]'),
  ('erdos-1089', 'Erdős Problem 1089', 'The problem tracked as Erdős 1089 was resolved by an AI-generated argument.', 'proved', 'new-result', 'Number theory', '2026-02-01', 'Aletheia', 'Generated the successful proof.', 'Mathematicians checked the proof and the community tracker recorded the resolution.', 'Expert-checked and tracker-confirmed.', 'expert', 'The compact summary intentionally defers the technical statement to the canonical problem page.', 0, '["Erdős 1089","number theory"]'),
  ('erdos-846-rediscovery', 'Erdős Problem 846: formal proof and independent rediscovery', 'AI systems produced a Lean-checked solution, but comparable prior literature from 2024 was identified afterward.', 'proved', 'rediscovery', 'Number theory', '2026-02-25', 'DeepMind prover and OpenAI internal model', 'Produced a formal proof and an independent derivation.', 'Experts compared the result against existing literature and updated the novelty assessment.', 'Lean checking plus independent derivation.', 'formal', 'This is catalogued as rediscovery/formalization, not a new-priority theorem.', 0, '["Erdős 846","rediscovery","Lean"]'),
  ('erdos-848-density-estimate', 'Erdős Problem 848 via a machine-suggested density estimate', 'GPT-5 supplied a key density estimate that was refined by mathematicians into a complete proof.', 'proved', 'human-ai', 'Combinatorics', '2025-08-07', 'GPT-5', 'Suggested the central density estimate and intermediate arguments.', 'Ashwin Sah and Mehtaab Sawhney refined the estimate and completed and verified the proof.', 'Human-checked research proof reported by OpenAI and the problem tracker.', 'expert', 'The AI contribution was decisive but did not by itself constitute the final proof.', 0, '["Erdős 848","density estimate","human-AI"]'),
  ('knot-signature-natural-slope', 'Knot signature from a newly identified natural slope', 'Machine-learning-guided pattern detection led to a proved exact relationship between a knot’s geometry and its signature.', 'discovered', 'human-ai', 'Topology', '2021-12-01', 'DeepMind supervised learning models', 'Detected a predictive geometric quantity that researchers named the natural slope.', 'András Juhász and Marc Lackenby formulated and proved the theorem.', 'Human proof published with the Nature research program.', 'published', 'The model guided discovery; the theorem was proved by human mathematicians.', 0, '["knot theory","signature","machine learning"]'),
  ('combinatorial-invariance-kl-polynomials', 'Combinatorial invariance for Kazhdan–Lusztig polynomials', 'AI-guided experimentation helped formulate an explicit combinatorial formula and an algorithm supporting a longstanding representation-theory conjecture.', 'discovered', 'human-ai', 'Representation theory', '2021-12-01', 'DeepMind graph neural networks', 'Identified structures and patterns that guided the conjectural formula.', 'Geordie Williamson and collaborators interpreted the patterns and developed the mathematics.', 'Computational checks on more than three million examples and peer-reviewed publication.', 'published', 'The evidence strongly supports the conjectural formula but computational verification is not a general proof.', 0, '["Kazhdan–Lusztig","representation theory","GNN"]'),
  ('alphatensor-matrix-multiplication', 'AlphaTensor matrix-multiplication algorithms', 'Reinforcement learning found provably correct matrix-multiplication algorithms, including a 4×5 by 5×5 construction using 76 scalar multiplications instead of the previous 80.', 'discovered', 'new-result', 'Algorithms', '2022-10-05', 'AlphaTensor', 'Searched the tensor-decomposition space for lower-rank algorithms.', 'Researchers verified the algorithms and analyzed their complexity.', 'Provably correct constructions published in Nature.', 'published', 'These are size- and field-specific algorithmic records, not a universal improvement to matrix multiplication exponent bounds.', 0, '["matrix multiplication","algorithms","reinforcement learning"]'),
  ('funsearch-cap-sets', 'FunSearch cap-set constructions', 'FunSearch produced larger cap sets in several finite-vector-space settings, improving known constructions in a mature extremal-combinatorics problem.', 'discovered', 'new-result', 'Extremal combinatorics', '2023-12-14', 'FunSearch with PaLM 2', 'Iteratively generated programs scored by an automated evaluator.', 'Researchers designed the evaluator, verified outputs, and interpreted the constructions.', 'Exact executable constructions with peer-reviewed reporting.', 'published', 'The work improves lower-bound constructions in selected settings; it does not solve the general cap-set problem.', 0, '["cap set","FunSearch","program synthesis"]'),
  ('alphaevolve-four-by-four', 'AlphaEvolve 4×4 complex matrix multiplication', 'AlphaEvolve found an algorithm multiplying 4×4 complex matrices using 48 scalar multiplications.', 'discovered', 'new-result', 'Algorithms', '2025-05-14', 'AlphaEvolve', 'Evolved and evaluated candidate algorithms.', 'DeepMind researchers verified and reported the construction.', 'Exact algorithm evaluated by deterministic checkers.', 'published', 'The result is for a specific matrix size and coefficient setting.', 0, '["matrix multiplication","AlphaEvolve","algorithms"]'),
  ('alphaevolve-kissing-number-11', 'AlphaEvolve lower bound for the 11-dimensional kissing number', 'A new configuration established a lower bound of at least 593 for the kissing number in dimension 11.', 'discovered', 'new-result', 'Discrete geometry', '2025-05-14', 'AlphaEvolve', 'Searched for improved geometric configurations using automated evaluators.', 'Researchers verified the construction and benchmarked it against prior bounds.', 'Deterministically checked construction reported by DeepMind.', 'published', 'This improves a lower bound; it does not determine the exact 11-dimensional kissing number.', 0, '["kissing number","sphere packing","AlphaEvolve"]'),
  ('gradient-descent-step-size', 'Larger stable step size for convex gradient descent', 'GPT-5 Pro helped improve the provable constant step-size guarantee beyond 1/L, with an optimal bound subsequently identified and checked.', 'proved', 'human-ai', 'Optimization', '2025-08-20', 'GPT-5 Pro', 'Generated proof ideas and algebra leading to the sharper guarantee.', 'Sébastien Bubeck and collaborators tested, corrected, and verified the result.', 'Expert mathematical verification and public derivation.', 'expert', 'The public announcement distinguishes intermediate AI suggestions from the final checked theorem.', 0, '["gradient descent","convex optimization","step size"]'),
  ('nesterov-stability', 'Stability of Nesterov accelerated gradient', 'A human–AI collaboration resolved a longstanding stability question for Nesterov’s accelerated gradient method.', 'proved', 'human-ai', 'Optimization', '2025-11-24', 'GPT-5', 'Suggested routes, lemmas, and calculations, some of which required correction.', 'Ernest Ryu selected the viable approach and verified and completed the proof.', 'Expert-authored and checked mathematical account.', 'expert', 'This was an iterative collaboration; the source explicitly records unsuccessful AI steps.', 0, '["Nesterov acceleration","stability","optimization"]'),
  ('sphere-packing-formalization', 'Formalization of the 8- and 24-dimensional sphere-packing theorems', 'The previously known Viazovska and Cohn–Kumar–Miller–Radchenko–Viazovska proofs were formalized in Lean at large scale.', 'formalized', 'formalization', 'Discrete geometry', '2026-07-01', 'Gauss', 'Filled many Lean proof goals from a human-designed blueprint.', 'A large team designed the formalization, decomposed the proof, reviewed code, and integrated contributions.', 'Lean kernel checking across roughly 200,000 lines.', 'formal', 'This formalizes 2016 theorems; it is not a new proof of the sphere-packing bounds.', 0, '["sphere packing","Lean","formalization"]'),
  ('kawauchi-mod-four-factorization', 'Mod-4 factorization in Kawauchi’s knot-polynomial conjecture', 'A mod-4 version of a 2006 knot-polynomial factorization conjecture was proved with substantial language-model assistance.', 'proved', 'human-ai', 'Topology', '2026-07-21', 'Claude Fable 5', 'Suggested constructions and proof steps used in the argument.', 'Jim Conant formulated, checked, and authored the preprint.', 'Author-checked public preprint.', 'expert', 'The stronger integral factorization statement is false; this entry is only the mod-4 theorem.', 0, '["knot theory","Kawauchi","polynomials"]'),
  ('qed-local-invariant-cycles', 'Integral local invariant cycles in degree one', 'A multi-agent theorem-proving system produced a proof of an integral degree-one local-invariant-cycles statement posed for the evaluation.', 'proved', 'new-result', 'Algebraic geometry', '2026-04-28', 'QED multi-agent system', 'Coordinated conjecture analysis, proof search, critique, and revision.', 'Experts posed the problem and reviewed the resulting proof.', 'Expert-reviewed preprint evidence.', 'expert', 'The problem was newly posed in the evaluation setting; broader variants are not claimed.', 0, '["local invariant cycles","multi-agent","algebraic geometry"]'),
  ('alphageometry-olympiad', 'AlphaGeometry olympiad geometry benchmark', 'AlphaGeometry solved 25 of 30 historical olympiad geometry problems under the study protocol, approaching elite human performance.', 'benchmark', 'capability', 'Geometry', '2024-01-17', 'AlphaGeometry', 'Combined a neural language model with symbolic deduction.', 'Researchers designed the benchmark and formally checked generated solutions.', 'Machine-checkable solutions to known problems.', 'published', 'These were known competition problems, not new mathematical theorems.', 0, '["geometry","olympiad","benchmark"]'),
  ('imo-2024-silver', 'AI systems reach silver-medal level at IMO 2024', 'AlphaProof and AlphaGeometry 2 solved four of six International Mathematical Olympiad problems for a score equivalent to a silver medal.', 'benchmark', 'capability', 'Olympiad mathematics', '2024-07-25', 'AlphaProof and AlphaGeometry 2', 'Generated formal or verifiable solutions to held-out competition problems.', 'IMO experts scored the solutions under the published protocol.', 'Expert scoring and formal verification where applicable.', 'published', 'This is a capability benchmark on known contest problems, not original research discovery.', 0, '["IMO","benchmark","formal proof"]');

INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'announcement', 'Levent Alpöge’s original X announcement', 'https://x.com/__alpoge__/status/2079028340955197566', 1 FROM records WHERE slug='jacobian-counterexample-dimension-three';
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'formal-proof', 'Independent Lean verification repository', 'https://github.com/deancureton/jacobian', 1 FROM records WHERE slug='jacobian-counterexample-dimension-three';
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'expert-review', 'Terence Tao’s digestion of the counterexample', 'https://terrytao.wordpress.com/2026/07/21/a-digestion-of-the-jacobian-conjecture-counterexample/', 1 FROM records WHERE slug='jacobian-counterexample-dimension-three';

INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'announcement', 'OpenAI: model disproves a discrete geometry conjecture', 'https://openai.com/index/model-disproves-discrete-geometry-conjecture/', 1 FROM records WHERE slug='erdos-unit-distance-conjecture';

INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'paper', 'AlphaProof Nexus paper', 'https://arxiv.org/abs/2605.22763', 1 FROM records WHERE slug IN ('alphaproof-nexus-open-problems','pure-o-sequences-log-concavity');
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'formal-proof', 'AlphaProof Nexus public Lean outputs', 'https://github.com/google-deepmind/alphaproof-nexus-results', 1 FROM records WHERE slug IN ('alphaproof-nexus-open-problems','pure-o-sequences-log-concavity');

INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'project', 'First Proof project and submissions', 'https://1stproof.org/', 1 FROM records WHERE slug IN ('first-proof-blind-refereeing','first-proof-hilbert-series-hooks');
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'paper', 'First Proof study report', 'https://1stproof.org/assets/docs/report.pdf', 1 FROM records WHERE slug IN ('first-proof-blind-refereeing','first-proof-hilbert-series-hooks');

INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'paper', 'Eight Problems from the Kourovka Notebook', 'https://arxiv.org/abs/2607.17477', 1 FROM records WHERE slug='kourovka-eight-problems';
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'paper', 'Autonomous resolution of Anderson’s question', 'https://arxiv.org/abs/2604.03789', 1 FROM records WHERE slug='anderson-quasi-completeness';
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'paper', 'AxiomProver proves Fel’s conjecture', 'https://arxiv.org/abs/2602.03716', 1 FROM records WHERE slug='fel-polynomial-conjecture';
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'formal-proof', 'Fel polynomial Lean source', 'https://github.com/AxiomMath/fel-polynomial', 1 FROM records WHERE slug='fel-polynomial-conjecture';
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'announcement', 'Axiom Math original X announcement', 'https://x.com/axiommathai/status/2019449659807219884', 1 FROM records WHERE slug='fel-polynomial-conjecture';
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'paper', 'A partial Vandiver theorem for almost all primes', 'https://arxiv.org/abs/2602.05090', 1 FROM records WHERE slug='partial-vandiver-density-one';
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'paper', 'Autonomous resolution of Erdős Problem 728', 'https://arxiv.org/abs/2601.07421', 1 FROM records WHERE slug='erdos-728-factorial-divisibility';

INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'problem', 'Canonical Erdős Problems entry', 'https://www.erdosproblems.com/728', 1 FROM records WHERE slug='erdos-728-factorial-divisibility';
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'problem', 'Canonical Erdős Problems entry', 'https://www.erdosproblems.com/659', 1 FROM records WHERE slug='erdos-659-few-distances';
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'problem', 'Canonical Erdős Problems entry', 'https://www.erdosproblems.com/960', 1 FROM records WHERE slug='erdos-960';
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'problem', 'Canonical Erdős Problems entry', 'https://www.erdosproblems.com/1089', 1 FROM records WHERE slug='erdos-1089';
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'problem', 'Canonical Erdős Problems entry', 'https://www.erdosproblems.com/846', 1 FROM records WHERE slug='erdos-846-rediscovery';
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'problem', 'Canonical Erdős Problems entry', 'https://www.erdosproblems.com/848', 1 FROM records WHERE slug='erdos-848-density-estimate';
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'expert-review', 'Community ledger of AI contributions to Erdős problems', 'https://github.com/teorth/erdosproblems/wiki/AI-contributions-to-Erd%C5%91s-problems', 1 FROM records WHERE slug IN ('erdos-659-few-distances','erdos-960','erdos-1089','erdos-846-rediscovery','erdos-848-density-estimate');

INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'paper', 'DeepMind: discoveries in pure mathematics', 'https://deepmind.google/blog/exploring-the-beauty-of-pure-mathematics-in-novel-ways/', 1 FROM records WHERE slug IN ('knot-signature-natural-slope','combinatorial-invariance-kl-polynomials');
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'paper', 'DeepMind: AlphaTensor', 'https://deepmind.google/blog/discovering-novel-algorithms-with-alphatensor/', 1 FROM records WHERE slug='alphatensor-matrix-multiplication';
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'paper', 'DeepMind: FunSearch', 'https://deepmind.google/blog/funsearch-making-new-discoveries-in-mathematical-sciences-using-large-language-models/', 1 FROM records WHERE slug='funsearch-cap-sets';
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'paper', 'DeepMind: AlphaEvolve', 'https://deepmind.google/blog/alphaevolve-a-gemini-powered-coding-agent-for-designing-advanced-algorithms/', 1 FROM records WHERE slug IN ('alphaevolve-four-by-four','alphaevolve-kissing-number-11');

INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'announcement', 'Sébastien Bubeck’s original X thread', 'https://x.com/SebastienBubeck/status/1958198661139009862', 1 FROM records WHERE slug='gradient-descent-step-size';
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'paper', 'OpenAI: accelerating science with GPT-5', 'https://openai.com/index/accelerating-science-gpt-5/', 1 FROM records WHERE slug IN ('gradient-descent-step-size','erdos-848-density-estimate');
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'paper', 'OpenAI: GPT-5 mathematical discovery', 'https://openai.com/index/gpt-5-mathematical-discovery/', 1 FROM records WHERE slug='nesterov-stability';

INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'project', 'The Fundamental Theor3m formalization project', 'https://thefundamentaltheor3m.github.io/', 1 FROM records WHERE slug='sphere-packing-formalization';
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'paper', 'A mod-4 factorization theorem for Kawauchi’s conjecture', 'https://arxiv.org/abs/2607.18655', 1 FROM records WHERE slug='kawauchi-mod-four-factorization';
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'paper', 'QED multi-agent theorem-proving paper', 'https://arxiv.org/abs/2604.24021', 1 FROM records WHERE slug='qed-local-invariant-cycles';
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'expert-review', 'Xena Project expert account of the group-scheme counterexample', 'https://xenaproject.wordpress.com/2026/07/20/human-mathematicians-are-being-outcounterexampled/', 1 FROM records WHERE slug='grothendieck-group-scheme-counterexample';

INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'paper', 'DeepMind: AlphaGeometry', 'https://deepmind.google/blog/alphageometry-an-olympiad-level-ai-system-for-geometry/', 1 FROM records WHERE slug='alphageometry-olympiad';
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'paper', 'DeepMind: IMO silver-medal-level result', 'https://deepmind.google/blog/ai-solves-imo-problems-at-silver-medal-level/', 1 FROM records WHERE slug='imo-2024-silver';

INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'paper', 'The Maxwell Conjecture is False', 'https://arxiv.org/abs/2607.27197', 1 FROM records WHERE slug='maxwell-point-charge-counterexample';

INSERT INTO records
  (slug, title, summary, outcome, novelty, domain, event_date, ai_system, ai_role, human_role, verification, verification_tier, caveat, featured, tags_json)
VALUES
  ('feige-conjecture', 'Feige’s conjecture on sums of nonnegative random variables', 'A short proof established Feige’s lower bound: for independent nonnegative mean-one variables, the probability their sum is below n+1 is at least (n/(n+1))^n.', 'proved', 'human-ai', 'Probability', '2026-07-27', 'GPT-5.6 Sol', 'Assisted in obtaining the short proof and connecting it to recent work on Gaffke’s conjecture.', 'Zipei Nie and Jiaye Wei checked, wrote, and released the argument.', 'Author-checked public preprint.', 'expert', 'The precise degree of AI autonomy is not quantified beyond the authors’ assistance statement.', 0, '["Feige conjecture","probability","inequalities"]');
INSERT INTO sources (record_id, kind, title, url, is_primary)
SELECT id, 'paper', 'On Feige’s conjecture', 'https://arxiv.org/abs/2607.24528', 1 FROM records WHERE slug='feige-conjecture';
